
export const statusEffects = [
	{
		id: "grappled",
		// _id: 'grappld'.padEnd(16,0),
		name: "SKYFALL.CONDITIONS.GRAPPLED",
		description: "SKYFALL.CONDITIONS.GRAPPLEDHINT",
		img: "icons/svg/trap.svg",
		// statuses: ["grappled"],
		changes: [{key:'test',mode:0,value:'10'}],
		disabled: false,
	},
	{
		id: "grappling",
		// _id: "grappling".padEnd(16,0),
		name: "SKYFALL.CONDITIONS.GRAPPLING",
		description: "SKYFALL.CONDITIONS.GRAPPLINGHINT",
		img: "icons/svg/trap.svg",
		// statuses: ["grappling"],
		changes: [],
		disabled: false,
	},
	{
		id: "frightened",
		// _id: "frightened".padEnd(16,0),
		name: "SKYFALL.CONDITIONS.FRIGHTENED",
		description: "SKYFALL.CONDITIONS.FRIGHTENEDHINT",
		img: "icons/svg/terror.svg",
		// statuses: ["frightened"],
		changes: [],
		disabled: false,
	},
	{
		id: "stunned",
		// _id: "stunned".padEnd(16,0),
		name: "SKYFALL.CONDITIONS.STUNNED",
		description: "SKYFALL.CONDITIONS.STUNNEDHINT",
		img: "icons/svg/stoned.svg",
		// statuses: ["stunned"],
		changes: [],
		disabled: false,
	},
	{
		id: "prone",
		// _id: "prone".padEnd(16,0),
		name: "SKYFALL.CONDITIONS.PRONE",
		description: "SKYFALL.CONDITIONS.PRONEHINT",
		img: "icons/svg/falling.svg",
		// statuses: ["prone"],
		changes: [],
		disabled: false,
	},
	{
		id: "restrained",
		// _id: "restrained".padEnd(16,0),
		name: "SKYFALL.CONDITIONS.RESTRAINED",
		description: "SKYFALL.CONDITIONS.RESTRAINEDHINT",
		img: "icons/svg/net.svg",
		// statuses: ["restrained"],
		changes: [],
		disabled: false,
	},
	{
		id: "unprotected",
		// _id: "unprotected".padEnd(16,0),
		name: "SKYFALL.CONDITIONS.UNPROTECTED",
		description: "SKYFALL.CONDITIONS.UNPROTECTEDHINT",
		img: "icons/svg/daze.svg",
		// statuses: ["unprotected"],
		changes: [],
		disabled: false,
		flags: {skyfall:{group:true}},
		disabled: false,
		system: {
			group: {
				all: false, physical:false, mental:false,
				str: false, dex: false, con: false,
				int: false, wis: false, cha: false
			},
			changes: [
				{
					key: "enemy-check[]", mode: "0", value:"disadvantage",
				}
			]
		},
	},
	{
		id: "disoriented",
		// _id: "disoriented".padEnd(16,0),
		name: "SKYFALL.CONDITIONS.DISORIENTED",
		description: "SKYFALL.CONDITIONS.DISORIENTEDHINT",
		img: "icons/svg/daze.svg",
		// statuses: ["disoriented"],
		changes: [],
		disabled: false,
	},
	{
		id: "burning",
		// _id: "burning".padEnd(16,0),
		name: "SKYFALL.CONDITIONS.BURNING",
		description: "SKYFALL.CONDITIONS.BURNINGHINT",
		img: "icons/svg/fire.svg",
		// statuses: ["burning"],
		changes: [
			{key: "dot", mode:0, value: "(@stack)d6[fire]" }
		],
		disabled: false,
		system: {
			stack: 1
		}
	},
	{
		id: "charmed",
		// _id: "charmed".padEnd(16,0),
		name: "SKYFALL.CONDITIONS.CHARMED",
		description: "SKYFALL.CONDITIONS.CHARMEDHINT",
		img: "icons/svg/daze.svg",
		// statuses: ["charmed"],
		changes: [],
		disabled: false,
	},
	{
		id: "poisoned",
		// _id: "poisoned".padEnd(16,0),
		name: "SKYFALL.CONDITIONS.POISONED",
		description: "SKYFALL.CONDITIONS.POISONEDHINT",
		img: "icons/svg/poison.svg",
		tint: "#00FF00",
		// statuses: ["poisoned"],
		changes: [],
		disabled: false,
	},
	{
		id: "incapacitated",
		// _id: "incapacitated".padEnd(16,0),
		name: "SKYFALL.CONDITIONS.INCAPACITATED",
		description: "SKYFALL.CONDITIONS.INCAPACITATEDHINT",
		img: "icons/svg/sleep.svg",
		// statuses: ["incapacitated"],
		changes: [],
		disabled: false,
	},
	{
		id: "unconscious",
		// _id: "unconscious".padEnd(16,0),
		name: "SKYFALL.CONDITIONS.UNCONSCIOUS",
		description: "SKYFALL.CONDITIONS.UNCONSCIOUSHINT",
		img: "icons/svg/unconscious.svg",
		// statuses: ["unconscious"],
		changes: [],
		disabled: false,
	},
	{
		id: "inspired",
		// _id: "inspired".padEnd(16,0),
		name: "SKYFALL.CONDITIONS.INSPIRED",
		description: "SKYFALL.CONDITIONS.INSPIREDHINT",
		img: "icons/svg/sun.svg",
		// statuses: ["inspired"],
		changes: [],
		disabled: false,
	},
	{
		id: "invisible",
		// _id: "invisible".padEnd(16,0),
		name: "SKYFALL.CONDITIONS.INVISIBLE",
		description: "SKYFALL.CONDITIONS.INVISIBLEHINT",
		img: "icons/svg/invisible.svg",
		// statuses: ["invisible"],
		changes: [],
		disabled: false,
	},
	{
		id: "marked",
		// _id: "marked".padEnd(16,0),
		name: "SKYFALL.CONDITIONS.MARKED",
		description: "SKYFALL.CONDITIONS.MARKEDHINT",
		img: "icons/svg/target.svg",
		// statuses: ["marked"],
		changes: [],
		disabled: false,
		system: {
			stack: 1
		}
	},
	{
		id: "hurt",
		// _id: "hurt".padEnd(16,0),
		name: "SKYFALL.CONDITIONS.HURT",
		description: "SKYFALL.CONDITIONS.HURTHINT",
		img: "icons/svg/degen.svg",
		// statuses: ["hurt"],
		changes: [],
		disabled: false,
	},
	{
		id: "dead",
		name: "SKYFALL.CONDITIONS.DEAD",
		img: "icons/svg/skull.svg",
	},
	{
		id: "paralyzed",
		// _id: "paralyzed".padEnd(16,0),
		name: "SKYFALL.CONDITIONS.PARALYZED",
		description: "SKYFALL.CONDITIONS.PARALYZEDHINT",
		img: "icons/svg/anchor.svg",
		// statuses: ["paralyzed"],
		changes: [],
		disabled: false,
	},
	{
		id: "petrified",
		// _id: "petrified".padEnd(16,0),
		name: "SKYFALL.CONDITIONS.PETRIFIED",
		description: "SKYFALL.CONDITIONS.PETRIFIEDHINT",
		img: "icons/svg/statue.svg",
		// statuses: ["petrified"],
		changes: [],
		disabled: false,
	},
	{
		id: "protected",
		// _id: "protected".padEnd(16,0),
		name: "SKYFALL.CONDITIONS.PROTECTED",
		description: "SKYFALL.CONDITIONS.PROTECTEDHINT",
		img: "icons/svg/shield.svg",
		// statuses: ["protected"],
		changes: [],
		flags: {skyfall:{group:true}},
		disabled: false,
		system: {
			group: {
				all: false, physical:false, mental:false,
				str: false, dex: false, con: false,
				int: false, wis: false, cha: false
			},
			changes: [
				{
					key: "enemy-check[]", mode: "0", value:"disadvantage",
				}
			]
		},
	},
	{
		id: "provoked",
		// _id: "provoked".padEnd(16,0),
		name: "SKYFALL.CONDITIONS.PROVOKED",
		description: "SKYFALL.CONDITIONS.PROVOKEDHINT",
		img: "icons/svg/eye.svg",
		// statuses: ["provoked"],
		changes: [],
		disabled: false,
	}
]