
export const statusEffects = [
	{
		id: "grappled",
		// _id: 'grappld'.padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Grappled",
		label: "SKYFALL2.CONDITIONS.Grappled",
		description: "SKYFALL2.CONDITIONS.GrappledHint",
		img: "systems/skyfall/icons/conditions/grappled.svg",
		// statuses: ["grappled", "restrained"],
		changes: [],
		disabled: false,
	},
	{
		id: "grappling",
		// _id: "grappling".padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Grappling",
		label: "SKYFALL2.CONDITIONS.Grappling",
		description: "SKYFALL2.CONDITIONS.GrapplingHint",
		img: "systems/skyfall/icons/conditions/grappling.svg",
		// statuses: ["grappling"],
		changes: [
			{key: "system.movement.walk", mode:1, value:0.5 },
			{key: "system.movement.swim", mode:1, value:0.5 },
			{key: "system.movement.burrow", mode:1, value:0.5 },
			{key: "system.movement.flight", mode:1, value:0.5 },
		],
		disabled: false,
	},
	{
		id: "frightened",
		// _id: "frightened".padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Frightened",
		label: "SKYFALL2.CONDITIONS.Frightened",
		description: "SKYFALL2.CONDITIONS.FrightenedHint",
		img: "icons/svg/terror.svg",
		// statuses: ["frightened"],
		changes: [
			{key: "system.modifiers.roll.ability", mode:2, value:'kl'},
			{key: "system.modifiers.roll.attack", mode:2, value:'kl'},
		],
		disabled: false,
	},
	{
		id: "stunned",
		// _id: "stunned".padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Stunned",
		label: "SKYFALL2.CONDITIONS.Stunned",
		description: "SKYFALL2.CONDITIONS.StunnedHint",
		img: "icons/svg/stoned.svg",
		img: "systems/skyfall/icons/conditions/stunned.svg",
		// statuses: ["incapacitated","unprotected"],
		changes: [],
		disabled: false,
	},
	{
		id: "prone",
		// _id: "prone".padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Prone",
		label: "SKYFALL2.CONDITIONS.Prone",
		description: "SKYFALL2.CONDITIONS.ProneHint",
		img: "icons/svg/falling.svg",
		changes: [
			{key: "system.modifiers.roll.attack", mode:2, value:'kl'},
		],
		changes: [],
		disabled: false,
	},
	{
		id: "restrained",
		// _id: "restrained".padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Restrained",
		label: "SKYFALL2.CONDITIONS.Restrained",
		description: "SKYFALL2.CONDITIONS.RestrainedHint",
		img: "icons/svg/net.svg",
		// statuses: ["unprotected-physical"],
		changes: [
			{key: "system.movement.walk", mode:1, value:0 },
			{key: "system.movement.swim", mode:1, value:0 },
			{key: "system.movement.burrow", mode:1, value:0 },
			{key: "system.movement.flight", mode:1, value:0 },
			{key: "system.modifiers.roll.attack", mode:2, value:'kl'},
		],
		changes: [],
		disabled: false,
	},
	{
		id: "concentrating",
		// _id: "concentrating".padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Concentrating",
		label: "SKYFALL2.CONDITIONS.Concentrating",
		description: "SKYFALL2.CONDITIONS.ConcentratingHint",
		img: "icons/svg/angel.svg",
		// statuses: ["concentrating"],
		changes: [],
		disabled: false,
	},
	{
		id: "unprotected",
		// _id: "unprotected".padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Unprotected",
		label: "SKYFALL2.CONDITIONS.Unprotected",
		description: "SKYFALL2.CONDITIONS.UnprotectedHint",
		img: "systems/skyfall/icons/conditions/unprotected.svg",
		
		// statuses: ["unprotected"],
		changes: [],
		disabled: false,
		system: {
			group: {
				all: false, physical:false, mental:false,
				str: false, dex: false, con: false,
				int: false, wis: false, cha: false
			},
		},
	},
	{
		id: "disoriented",
		// _id: "disoriented".padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Disoriented",
		label: "SKYFALL2.CONDITIONS.Disoriented",
		description: "SKYFALL2.CONDITIONS.DisorientedHint",
		img: "icons/svg/daze.svg",
		// statuses: ["unprotected"],
		changes: [
			{key: "system.modifiers.roll.attack", mode:2, value:'kl'},
		],
		disabled: false,
	},
	{
		id: "burning",
		// _id: "burning".padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Burning",
		label: "SKYFALL2.CONDITIONS.Burning",
		description: "SKYFALL2.CONDITIONS.BurningHint",
		img: "icons/svg/fire.svg",
		// statuses: ["burning"],
		changes: [
			{key: "dot", mode:0, value: "(@stack)d6[fire]" }
		],
		disabled: false,
		system: {
			stack: 1
		}
	},
	{
		id: "charmed",
		// _id: "charmed".padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Charmed",
		label: "SKYFALL2.CONDITIONS.Charmed",
		description: "SKYFALL2.CONDITIONS.CharmedHint",
		img: "systems/skyfall/icons/conditions/charmed.svg",
		// statuses: ["charmed"],
		changes: [
		],
		disabled: false,
	},
	{
		id: "poisoned",
		// _id: "poisoned".padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Poisoned",
		label: "SKYFALL2.CONDITIONS.Poisoned",
		description: "SKYFALL2.CONDITIONS.PoisonedHint",
		img: "icons/svg/poison.svg",
		tint: "#00FF00",
		// statuses: ["poisoned"],
		changes: [
			{key: "system.modifiers.roll.check", mode:2, value:'kl'},
		],
		disabled: false,
	},
	{
		id: "incapacitated",
		// _id: "incapacitated".padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Incapacitated",
		label: "SKYFALL2.CONDITIONS.Incapacitated",
		description: "SKYFALL2.CONDITIONS.IncapacitatedHint",
		img: "icons/svg/sleep.svg",
		// statuses: ["incapacitated"],
		changes: [],
		disabled: false,
	},
	{
		id: "unconscious",
		// _id: "unconscious".padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Unconscious",
		label: "SKYFALL2.CONDITIONS.Unconscious",
		description: "SKYFALL2.CONDITIONS.UnconsciousHint",
		img: "icons/svg/unconscious.svg",
		// statuses: ["incapacitated","prone","unprotected"],
		changes: [],
		disabled: false,
	},
	{
		id: "inspired",
		// _id: "inspired".padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Inspired",
		label: "SKYFALL2.CONDITIONS.Inspired",
		description: "SKYFALL2.CONDITIONS.InspiredHint",
		img: "icons/svg/sun.svg",
		img: "systems/skyfall/icons/conditions/inspired.svg",
		// statuses: ["inspired"],
		changes: [],
		disabled: false,
	},
	{
		id: "invisible",
		// _id: "invisible".padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Invisible",
		label: "SKYFALL2.CONDITIONS.Invisible",
		description: "SKYFALL2.CONDITIONS.InvisibleHint",
		img: "icons/svg/invisible.svg",
		// statuses: ["invisible"],
		changes: [
			{key: "system.modifiers.roll.attack", mode:2, value:'kh'},
		],
		disabled: false,
	},
	{
		id: "marked",
		// _id: "marked".padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Marked",
		label: "SKYFALL2.CONDITIONS.Marked",
		description: "SKYFALL2.CONDITIONS.MarkedHint",
		img: "icons/svg/target.svg",
		// statuses: ["marked"],
		changes: [],
		disabled: false,
		system: {
			stack: 1
		}
	},
	{
		id: "hurt",
		// _id: "hurt".padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Hurt",
		label: "SKYFALL2.CONDITIONS.Hurt",
		description: "SKYFALL2.CONDITIONS.HurtHint",
		img: "icons/svg/degen.svg",
		// statuses: ["hurt"],
		changes: [],
		disabled: false,
	},
	{
		id: "dead",
		name: "SKYFALL2.CONDITIONS.Dead",
		label: "SKYFALL2.CONDITIONS.Dead",
		img: "icons/svg/skull.svg",
	},
	{
		id: "paralyzed",
		// _id: "paralyzed".padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Paralyzed",
		label: "SKYFALL2.CONDITIONS.Paralyzed",
		description: "SKYFALL2.CONDITIONS.ParalyzedHint",
		img: "icons/svg/anchor.svg",
		// statuses: ["incapacitated","unprotected"],
		changes: [],
		disabled: false,
	},
	{
		id: "petrified",
		// _id: "petrified".padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Petrified",
		label: "SKYFALL2.CONDITIONS.Petrified",
		description: "SKYFALL2.CONDITIONS.PetrifiedHint",
		img: "icons/svg/statue.svg",
		// statuses: ["incapacitated","unprotected"],
		changes: [
			{key: "system.modifiers.damage.taken.all", mode:5, value:'res'},
		],
		disabled: false,
	},
	{
		id: "protected",
		// _id: "protected".padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Protected",
		label: "SKYFALL2.CONDITIONS.Protected",
		description: "SKYFALL2.CONDITIONS.ProtectedHint",
		img: "icons/svg/shield.svg",
		// statuses: ["protected"],
		changes: [],
		disabled: false,
		system: {
			group: {
				all: false, physical:false, mental:false,
				str: false, dex: false, con: false,
				int: false, wis: false, cha: false
			},
		},
	},
	{
		id: "provoked",
		// _id: "provoked".padEnd(16,0),
		name: "SKYFALL2.CONDITIONS.Provoked",
		label: "SKYFALL2.CONDITIONS.Provoked",
		description: "SKYFALL2.CONDITIONS.ProvokedHint",
		img: "icons/svg/eye.svg",
		// statuses: ["provoked"],
		changes: [
			{key: "system.modifiers.roll.attack", mode:2, value:'kl'},
		],
		disabled: false,
	},
	{
		id: "encumbered",
		name: "SKYFALL2.CONDITIONS.Encumbered",
		description: "SKYFALL2.CONDITIONS.EncumberedHint",
		img: "systems/skyfall/icons/conditions/encumbered.svg",
		// statuses: ["encumbered"],
		changes: [
			{key: "system.movement.walk", mode:1, value:'0.5'},
			{key: "system.movement.swim", mode:1, value:'0.5'},
			{key: "system.movement.burrow", mode:1, value:'0.5'},
			{key: "system.movement.flight", mode:1, value:'0.5'},
			{key: "system.modifiers.roll.str", mode:2, value:'kl'},
			{key: "system.modifiers.roll.dex", mode:2, value:'kl'},
			{key: "system.modifiers.roll.con", mode:2, value:'kl'},
		],
		disabled: false,
	},
	{
		id: "arcaneoverload",
		name: "SKYFALL2.CONDITIONS.ArcaneOverload",
		description: "SKYFALL2.CONDITIONS.ArcaneOverloadHint",
		img: "systems/skyfall/icons/conditions/arcaneoverload.svg",
		changes: [ 
			{key: "system.modifiers.hp.totalExtra", mode:2, value:'0'},
		],
		disabled: false,
	},
]