export const statusEffects = [
	{
		id: "grappled",
		// _id: "grappled",
		name: "SKYFALL.CONDITIONS.GRAPPLED",
		description: "SKYFALL.CONDITIONS.GRAPPLEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["grappled"],
		changes: [],
		disabled: false,
	},
	{
		id: "grappling",
		// _id: "grappling",
		name: "SKYFALL.CONDITIONS.GRAPPLING",
		description: "SKYFALL.CONDITIONS.GRAPPLINGHINT",
		img: "icons/svg/daze.svg",
		statuses: ["grappling"],
		changes: [],
		disabled: false,
	},
	{
		id: "frightened",
		// _id: "frightened",
		name: "SKYFALL.CONDITIONS.FRIGHTENED",
		description: "SKYFALL.CONDITIONS.FRIGHTENEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["frightened"],
		changes: [],
		disabled: false,
	},
	{
		id: "stunned",
		// _id: "stunned",
		name: "SKYFALL.CONDITIONS.STUNNED",
		description: "SKYFALL.CONDITIONS.STUNNEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["stunned"],
		changes: [],
		disabled: false,
	},
	{
		id: "prone",
		// _id: "prone",
		name: "SKYFALL.CONDITIONS.PRONE",
		description: "SKYFALL.CONDITIONS.PRONEHINT",
		img: "icons/svg/daze.svg",
		statuses: ["prone"],
		changes: [],
		disabled: false,
	},
	{
		id: "restrained",
		// _id: "restrained",
		name: "SKYFALL.CONDITIONS.RESTRAINED",
		description: "SKYFALL.CONDITIONS.RESTRAINEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["restrained"],
		changes: [],
		disabled: false,
	},
	{
		id: "unprotected",
		// _id: "unprotected",
		name: "SKYFALL.CONDITIONS.UNPROTECTED",
		description: "SKYFALL.CONDITIONS.UNPROTECTEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["unprotected"],
		changes: [],
		disabled: false,
	},
	{
		id: "unprotected-phy",
		// _id: "unprotected-phy",
		name: "SKYFALL.CONDITIONS.UNPROTECTEDPHY",
		description: "SKYFALL.CONDITIONS.UNPROTECTEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["unprotected-phy"],
		changes: [],
		disabled: false,
	},
	{
		id: "unprotected-men",
		// _id: "unprotected-men",
		name: "SKYFALL.CONDITIONS.UNPROTECTEDMEN",
		description: "SKYFALL.CONDITIONS.UNPROTECTEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["unprotected-men"],
		changes: [],
		disabled: false,
	},
	{
		id: "unprotected-str",
		// _id: "unprotected-str",
		name: "SKYFALL.CONDITIONS.UNPROTECTEDSTR",
		description: "SKYFALL.CONDITIONS.UNPROTECTEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["unprotected-str"],
		changes: [],
		disabled: false,
	},
	{
		id: "unprotected-dex",
		// _id: "unprotected-dex",
		name: "SKYFALL.CONDITIONS.UNPROTECTEDDEX",
		description: "SKYFALL.CONDITIONS.UNPROTECTEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["unprotected-dex"],
		changes: [],
		disabled: false,
	},
	{
		id: "unprotected-con",
		// _id: "unprotected-con",
		name: "SKYFALL.CONDITIONS.UNPROTECTEDCON",
		description: "SKYFALL.CONDITIONS.UNPROTECTEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["unprotected-con"],
		changes: [],
		disabled: false,
	},
	{
		id: "unprotected-int",
		// _id: "unprotected-int",
		name: "SKYFALL.CONDITIONS.UNPROTECTEDINT",
		description: "SKYFALL.CONDITIONS.UNPROTECTEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["unprotected-int"],
		changes: [],
		disabled: false,
	},
	{
		id: "unprotected-wis",
		// _id: "unprotected-wis",
		name: "SKYFALL.CONDITIONS.UNPROTECTEDWIS",
		description: "SKYFALL.CONDITIONS.UNPROTECTEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["unprotected-wis"],
		changes: [],
		disabled: false,
	},
	{
		id: "unprotected-cha",
		// _id: "unprotected-cha",
		name: "SKYFALL.CONDITIONS.UNPROTECTEDCHA",
		description: "SKYFALL.CONDITIONS.UNPROTECTEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["unprotected-cha"],
		changes: [],
		disabled: false,
	},
	{
		id: "disoriented",
		// _id: "disoriented",
		name: "SKYFALL.CONDITIONS.DISORIENTED",
		description: "SKYFALL.CONDITIONS.DISORIENTEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["disoriented"],
		changes: [],
		disabled: false,
	},
	{
		id: "burning",
		// _id: "burning",
		name: "SKYFALL.CONDITIONS.BURNING",
		description: "SKYFALL.CONDITIONS.BURNINGHINT",
		img: "icons/svg/daze.svg",
		statuses: ["burning"],
		changes: [],
		disabled: false,
	},
	{
		id: "charmed",
		// _id: "charmed",
		name: "SKYFALL.CONDITIONS.CHARMED",
		description: "SKYFALL.CONDITIONS.CHARMEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["charmed"],
		changes: [],
		disabled: false,
	},
	{
		id: "poisoned",
		// _id: "poisoned",
		name: "SKYFALL.CONDITIONS.POISONED",
		description: "SKYFALL.CONDITIONS.POISONEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["poisoned"],
		changes: [],
		disabled: false,
	},
	{
		id: "exhaustion",
		// _id: "exhaustion",
		name: "SKYFALL.CONDITIONS.EXHAUSTION",
		description: "SKYFALL.CONDITIONS.EXHAUSTIONHINT",
		img: "icons/svg/daze.svg",
		statuses: ["exhaustion"],
		changes: [],
		disabled: false,
	},
	{
		id: "incapacitated",
		// _id: "incapacitated",
		name: "SKYFALL.CONDITIONS.INCAPACITATED",
		description: "SKYFALL.CONDITIONS.INCAPACITATEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["incapacitated"],
		changes: [],
		disabled: false,
	},
	{
		id: "unconscious",
		// _id: "unconscious",
		name: "SKYFALL.CONDITIONS.UNCONSCIOUS",
		description: "SKYFALL.CONDITIONS.UNCONSCIOUSHINT",
		img: "icons/svg/daze.svg",
		statuses: ["unconscious"],
		changes: [],
		disabled: false,
	},
	{
		id: "inspired",
		// _id: "inspired",
		name: "SKYFALL.CONDITIONS.INSPIRED",
		description: "SKYFALL.CONDITIONS.INSPIREDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["inspired"],
		changes: [],
		disabled: false,
	},
	{
		id: "invisible",
		// _id: "invisible",
		name: "SKYFALL.CONDITIONS.INVISIBLE",
		description: "SKYFALL.CONDITIONS.INVISIBLEHINT",
		img: "icons/svg/daze.svg",
		statuses: ["invisible"],
		changes: [],
		disabled: false,
	},
	{
		id: "marked",
		// _id: "marked",
		name: "SKYFALL.CONDITIONS.MARKED",
		description: "SKYFALL.CONDITIONS.MARKEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["marked"],
		changes: [],
		disabled: false,
	},
	{
		id: "hurt",
		// _id: "hurt",
		name: "SKYFALL.CONDITIONS.HURT",
		description: "SKYFALL.CONDITIONS.HURTHINT",
		img: "icons/svg/daze.svg",
		statuses: ["hurt"],
		changes: [],
		disabled: false,
	},
	{
		id: "paralyzed",
		// _id: "paralyzed",
		name: "SKYFALL.CONDITIONS.PARALYZED",
		description: "SKYFALL.CONDITIONS.PARALYZEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["paralyzed"],
		changes: [],
		disabled: false,
	},
	{
		id: "petrified",
		// _id: "petrified",
		name: "SKYFALL.CONDITIONS.PETRIFIED",
		description: "SKYFALL.CONDITIONS.PETRIFIEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["petrified"],
		changes: [],
		disabled: false,
	},
	{
		id: "protected",
		// _id: "protected",
		name: "SKYFALL.CONDITIONS.PROTECTED",
		description: "SKYFALL.CONDITIONS.PROTECTEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["protected"],
		changes: [],
		disabled: false,
	},
	{
		id: "protected-phy",
		// _id: "protected-phy",
		name: "SKYFALL.CONDITIONS.PROTECTEDPHY",
		description: "SKYFALL.CONDITIONS.PROTECTEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["protected-phy"],
		changes: [],
		disabled: false,
	},
	{
		id: "protected-men",
		// _id: "protected-men",
		name: "SKYFALL.CONDITIONS.PROTECTEDMEN",
		description: "SKYFALL.CONDITIONS.PROTECTEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["protected-men"],
		changes: [],
		disabled: false,
	},
	{
		id: "protected-str",
		// _id: "protected-str",
		name: "SKYFALL.CONDITIONS.PROTECTEDSTR",
		description: "SKYFALL.CONDITIONS.PROTECTEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["protected-str"],
		changes: [],
		disabled: false,
	},
	{
		id: "protected-dex",
		// _id: "protected-dex",
		name: "SKYFALL.CONDITIONS.PROTECTEDDEX",
		description: "SKYFALL.CONDITIONS.PROTECTEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["protected-dex"],
		changes: [],
		disabled: false,
	},
	{
		id: "protected-con",
		// _id: "protected-con",
		name: "SKYFALL.CONDITIONS.PROTECTEDCON",
		description: "SKYFALL.CONDITIONS.PROTECTEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["protected-con"],
		changes: [],
		disabled: false,
	},
	{
		id: "protected-int",
		// _id: "protected-int",
		name: "SKYFALL.CONDITIONS.PROTECTEDINT",
		description: "SKYFALL.CONDITIONS.PROTECTEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["protected-int"],
		changes: [],
		disabled: false,
	},
	{
		id: "protected-wis",
		// _id: "protected-wis",
		name: "SKYFALL.CONDITIONS.PROTECTEDWIS",
		description: "SKYFALL.CONDITIONS.PROTECTEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["protected-wis"],
		changes: [],
		disabled: false,
	},
	{
		id: "protected-cha",
		// _id: "protected-cha",
		name: "SKYFALL.CONDITIONS.PROTECTEDCHA",
		description: "SKYFALL.CONDITIONS.PROTECTEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["protected-cha"],
		changes: [],
		disabled: false,
	},
	{
		id: "provoked",
		// _id: "provoked",
		name: "SKYFALL.CONDITIONS.PROVOKED",
		description: "SKYFALL.CONDITIONS.PROVOKEDHINT",
		img: "icons/svg/daze.svg",
		statuses: ["provoked"],
		changes: [],
		disabled: false,
	}
]