# Adapted from Crucible and Draw Steel
# System Release Workflow

# Useful References:
#   - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#   - https://docs.github.com/en/actions/learn-github-actions/contexts
#   - https://docs.github.com/en/actions/learn-github-actions/environment-variables
#   - https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
#   - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
#   - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
# Notes
#   `github.event.release.tag_name` was used to get the tag name, but it returned empty

name: System Release Build

env:
  NODE_VERSION: 22
  LATEST_MANIFEST_URL: "https://github.com/${{github.repository}}/releases/latest/download/system.json"
  RELEASE_DOWNLOAD_URL: "https://github.com/${{github.repository}}/releases/download/${{ github.event.release.tag_name }}/skyfall.zip"

# Old:
# push:
#   tags:
#     - "release-*"

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: .npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline

      # Compile Database Packs, JavaScript, and CSS
      - name: Compile
        run: npm run build

      # Modify "system.json" with values specific to the release.
      - name: Modify Module Manifest With Release-Specific Values
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: "static/system.json"
        env:
          esmodules.0: "skyfall.mjs"
          manifest: ${{env.LATEST_MANIFEST_URL}}
          download: ${{env.RELEASE_DOWNLOAD_URL}}
          flags.hotReload: false


      # Create a "system.zip" archive containing all the system's required files.
      # zip --recurse-paths ./skyfall.zip dist/*
      - name: Create System Archive
        run: (cd dist; zip --recurse-paths ../skyfall.zip ./)

      # Update the GitHub release with the manifest and system archive files.
      - name: Update Release With Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: ${{ github.event.release.unpublished }}
          prerelease: ${{ github.event.release.prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './static/system.json, ./skyfall.zip'
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
